<Project>
	<PropertyGroup>
		<TargetFrameworks>net$(DotNet_Version_LTS);net$(DotNet_Version_STS)</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">net$(DotNet_Version_LTS)-windows10.0.19041.0;net$(DotNet_Version_STS)-windows10.0.19041.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
	</ItemGroup>
</Project>