name: CI
on:
  push:
    branches:
      - v3.x
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ windows-latest ]
        os: [ aigio-win10ltsc-vm ]
        
    steps:
      - name: Checkout repository
#        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          
#      - name: Checkout repository(BD.Git.Checkout.Tools)
#        if: ${{ matrix.os == 'aigio-win10ltsc-vm' }}
#        run: C:\actions-runner\checkout.exe ${{ github.workspace }} ${{ github.sha }} ${{ github.repositoryUrl }}

      - name: Setup .NET
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install Android SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install android

      - name: Install iOS SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install ios

      - name: Install macOS SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install macos

      - name: Install Mac Catalyst SDK
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install maccatalyst

      - name: Install Maui
        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
        run: dotnet workload install maui

#      - name: Install wasm-tools
#        if: ${{ matrix.os != 'aigio-win10ltsc-vm' }}
#        run: dotnet workload install wasm-tools

      - name: Restore Workload
        run: dotnet workload restore

      - name: Verify dotnet info
        run: dotnet --info

      - name: Build Debug
        run: dotnet build -c Debug BD.WTTS.MicroServices.ClientSDK.sln --nologo -v q /property:WarningLevel=1 

      - name: Build Release
        run: dotnet build -c Release BD.WTTS.MicroServices.ClientSDK.sln --nologo -v q /property:WarningLevel=1 

#  release:
#    name: Release
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Changelog
#        uses: glennawatson/ChangeLog@v1
#        id: changelog
#
#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          token: ${{ secrets.RMBADMIN_TOKEN }}
#          body: ${{ steps.changelog.outputs.commitLog }}
#          draft: false
#          prerelease: false
